backend:
  name: github
  repo: ARogala/rogala-designs

media_folder: static/assets
public_folder: assets

collections:
  - name: TechBlog
    label: TechBlog
    folder: src/techblog/JavaScript
    create: true
    fields:
      - { name: path, label: Path, default: src/techblog/JavaScript/ }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: author, label: Author }
      - { name: category, label: Category}
      - { name: subCategory, label: SubCategory}
      - { name: body, label: Body, widget: markdown }